name: Update Actions

on:
  push:
    branches: main
  schedule:
    - cron: "30 15 * * *"

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install
        run: yarn

      - name: Update
        run: node ./script/update-actions.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "github-bot@github.com"
          git config --global user.name "github-bot"
          git pull
          git add -A
          git commit -m "🤖 Auto updated actions" || exit 0
          git push
